# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ZU3_Exp.xdc

# XDC: new/AUP-ZU3.xdc

# Block Designs: bd/HDMI_PS2/HDMI_PS2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_PS2 || ORIG_REF_NAME==HDMI_PS2} -quiet] -quiet

# IP: bd/HDMI_PS2/ip/HDMI_PS2_HDMI_TX_0_0/HDMI_PS2_HDMI_TX_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_PS2_HDMI_TX_0_0 || ORIG_REF_NAME==HDMI_PS2_HDMI_TX_0_0} -quiet] -quiet

# IP: bd/HDMI_PS2/ip/HDMI_PS2_VideoTiming_0_0/HDMI_PS2_VideoTiming_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_PS2_VideoTiming_0_0 || ORIG_REF_NAME==HDMI_PS2_VideoTiming_0_0} -quiet] -quiet

# IP: bd/HDMI_PS2/ip/HDMI_PS2_clk_wiz_0_0/HDMI_PS2_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_PS2_clk_wiz_0_0 || ORIG_REF_NAME==HDMI_PS2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/HDMI_PS2/ip/HDMI_PS2_PS2_Mouse_0_0/HDMI_PS2_PS2_Mouse_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_PS2_PS2_Mouse_0_0 || ORIG_REF_NAME==HDMI_PS2_PS2_Mouse_0_0} -quiet] -quiet

# IP: bd/HDMI_PS2/ip/HDMI_PS2_OLED_ASCII_0_0/HDMI_PS2_OLED_ASCII_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_PS2_OLED_ASCII_0_0 || ORIG_REF_NAME==HDMI_PS2_OLED_ASCII_0_0} -quiet] -quiet

# IP: bd/HDMI_PS2/ip/HDMI_PS2_MouseCtrl_0_1/HDMI_PS2_MouseCtrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_PS2_MouseCtrl_0_1 || ORIG_REF_NAME==HDMI_PS2_MouseCtrl_0_1} -quiet] -quiet

# IP: bd/HDMI_PS2/ip/HDMI_PS2_OLED_GameInfo_0_0/HDMI_PS2_OLED_GameInfo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_PS2_OLED_GameInfo_0_0 || ORIG_REF_NAME==HDMI_PS2_OLED_GameInfo_0_0} -quiet] -quiet

# IP: bd/HDMI_PS2/ip/HDMI_PS2_ImgGen2_0_0/HDMI_PS2_ImgGen2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_PS2_ImgGen2_0_0 || ORIG_REF_NAME==HDMI_PS2_ImgGen2_0_0} -quiet] -quiet

# XDC: c:/Users/lab/Desktop/HDMI_PS2 ---- Kopia/HDMI_PS2.gen/sources_1/bd/HDMI_PS2/HDMI_PS2_ooc.xdc
